### ISSUE TITLE
error in plotter.py  and other modules 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bthcode/gdb-plot#2]
```

i  need help to fix errors

Type "apropos word" to search for commands related to "word"...
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/fayyaz/Documents/gdb-plot-0.4.1/plotter.py", line 10, in <module>
    from gp_data_extractor import *
  File "/home/fayyaz/Documents/gdb-plot-0.4.1/gp_data_extractor.py", line 26
    print arg
            ^
SyntaxError: invalid syntax



```

Original issue reported on code.google.com by `fsabai...@gmail.com` on 27 Mar 2014 at 12:24

**Comment by bthcode** [comment]
This looks to me like it was a python3 v. python2 issues.  I've gone through and made the code python3 safe.
